import React, { useState } from 'react';
import { Alert, StyleSheet, Text } from 'react-native';
import PaymentLayout from '../../components/payments/PaymentLayout';
import { PaymentField } from '../../components/payments/PaymentForm';
import { ConfirmationButton, MissingDataState, OutlineButton } from '../../components/ui';
import useAsyncAction from '../../hooks/useAsyncAction';
import { authorizePayment, schedulePayment } from '../../services/paymentService';
import { isSandboxMode } from '../../config';
import { colors, spacing, typography } from '../../theme';
export default function PaymentAuthorizationScreen({ navigation, route }) { const payment = route.params?.payment; const [password, setPassword] = useState(''); const [otp, setOtp] = useState(''); const [cvv, setCvv] = useState(''); const [requested, setRequested] = useState(false); const { execute: submitPayment, loading } = useAsyncAction(payment?.scheduled ? schedulePayment : authorizePayment); if (!payment) return <MissingDataState navigation={navigation} title="Autorizar pagamento" />; const request = () => { setRequested(true); Alert.alert('Token enviado', 'Digite o código de 6 dígitos enviado para o seu dispositivo.'); }; const pay = async () => { if (password.length < 4) return Alert.alert('Digite sua senha'); if (!isSandboxMode && payment.installmentData && !/^\d{3}$/.test(cvv)) return Alert.alert('Digite o CVV do cartão'); if (!requested) return request(); if (!/^\d{6}$/.test(otp)) return Alert.alert('Token inválido'); try { const authorizedPayment = await submitPayment(payment, otp); if (authorizedPayment) navigation.replace('PaymentReceipt', { payment: authorizedPayment }); } catch (error) { Alert.alert('Serviço indisponível', error?.message || 'Não foi possível autorizar o pagamento agora.'); } }; return <PaymentLayout navigation={navigation} title="Autorizar pagamento"><Text style={styles.value}>R$ {payment.bill.total}</Text><Text style={styles.recipient}>{payment.bill.beneficiary}</Text><PaymentField keyboardType="numeric" label="Senha" maxLength={6} onChangeText={setPassword} secureTextEntry value={password} />{!isSandboxMode && payment.installmentData ? <PaymentField keyboardType="numeric" label="CVV do cartão" maxLength={3} onChangeText={setCvv} secureTextEntry value={cvv} /> : null}{requested ? <PaymentField keyboardType="numeric" label="Token" maxLength={6} onChangeText={setOtp} value={otp} /> : <OutlineButton onPress={request}>Enviar token</OutlineButton>}<ConfirmationButton disabled={loading} loading={loading} onPress={pay} style={styles.pay}>Pagar</ConfirmationButton></PaymentLayout>; }
const styles = StyleSheet.create({ value: { ...typography.display, color: colors.textPrimary, marginTop: spacing.lg, textAlign: 'center' }, recipient: { ...typography.body, color: colors.textSecondary, marginBottom: spacing.xxl, marginTop: spacing.sm, textAlign: 'center' }, pay: { marginTop: spacing.md }, mock: { ...typography.caption, color: colors.textMuted, marginTop: spacing.lg, textAlign: 'center' } });
