import React from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import PaymentLayout from '../../components/payments/PaymentLayout';
import { Card, Icon, SectionTitle, ServiceCard } from '../../components/ui';
import { colors, spacing, typography } from '../../theme';
export default function PaymentStartScreen({ navigation }) { return <PaymentLayout navigation={navigation} title="Pagar conta"><Card elevated={false} style={styles.hero}><Image source={require('../../../assets/legacy/assets_icones_pagamentos.png')} style={styles.heroIcon} /><View style={styles.copy}><Text style={styles.title}>Pagamentos</Text><Text style={styles.subtitle}>Pague boletos e contas com código de barras.</Text></View></Card><SectionTitle style={styles.section} title="Como deseja pagar?" /><View style={styles.grid}><ServiceCard icon={<Icon color={colors.purple300} name="create-outline" size={22} />} label="Digitar código" onPress={() => navigation.navigate('PaymentCode', { source: 'manual' })} style={styles.option} /><ServiceCard icon={<Icon color={colors.purple300} name="barcode-outline" size={22} />} label="Ler código" onPress={() => navigation.navigate('PaymentScanner')} style={styles.option} /><ServiceCard icon={<Icon color={colors.purple300} name="calendar-outline" size={22} />} label="Pagamento parcelado" onPress={() => navigation.navigate('PaymentCode', { source: 'manual', installment: true })} style={styles.option} /></View><Text style={styles.note}>Fluxo original: NavScreen38 → NavScreen5 · Parcelado: NavScreen97</Text></PaymentLayout>; }
// "Dark glass": mesma linguagem visual do resto do app — fundo translúcido
// em vez de cor sólida, borda quase invisível, sombra própria.
const styles = StyleSheet.create({ hero: { alignItems: 'center', backgroundColor: 'rgba(12, 43, 76, 0.72)', borderColor: 'rgba(92, 142, 220, 0.10)', borderWidth: 1, flexDirection: 'row', padding: spacing.xl, shadowColor: '#000000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 4 }, heroIcon: { height: 44, tintColor: colors.orange400, width: 44 }, copy: { flex: 1, marginLeft: spacing.lg }, title: { ...typography.heading2, color: colors.textPrimary }, subtitle: { ...typography.body, color: colors.textSecondary, marginTop: 4 }, section: { marginBottom: spacing.md, marginTop: spacing.xxl }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, option: { backgroundColor: 'rgba(12, 43, 76, 0.72)', borderColor: 'rgba(92, 142, 220, 0.10)', shadowColor: '#000000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 4, width: '47%' }, note: { ...typography.caption, color: colors.textMuted, marginTop: spacing.xxl, textAlign: 'center' } });
