import React, { useState } from 'react';
import { Alert, StyleSheet, Text } from 'react-native';
import PaymentLayout from '../../components/payments/PaymentLayout';
import { PaymentField, PaymentInfoRow, PaymentToggle } from '../../components/payments/PaymentForm';
import { BalanceCard, Card, MissingDataState, PrimaryButton } from '../../components/ui';
import { getPaymentDetailsData, validatePayment } from '../../services/paymentService'; import useAsyncResource from '../../hooks/useAsyncResource';
import { colors, spacing, typography } from '../../theme';
import { paymentCurrencyToNumber, validatePaymentDate } from '../../utils/paymentValidation';
export default function PaymentDetailsScreen({ navigation, route }) { const {data: paymentData} = useAsyncResource(getPaymentDetailsData, {balance: ''}); const bill = route.params?.bill; const [amount, setAmount] = useState(bill?.total || ''); const [description, setDescription] = useState(''); const [scheduled, setScheduled] = useState(false); const [date, setDate] = useState(''); const [favorite, setFavorite] = useState(false); const [balance, setBalance] = useState(false); if (!bill) return <MissingDataState navigation={navigation} title="Dados do boleto" />; const next = async () => { if (paymentCurrencyToNumber(amount) <= 0) return Alert.alert('Informe o valor a pagar'); if (scheduled && !validatePaymentDate(date)) return Alert.alert('Informe uma data válida no formato DD/MM/AAAA'); const payment = { bill: { ...bill, total: amount }, description, scheduled, date, favorite, installment: Boolean(route.params?.installment), favoriteName: route.params?.favoriteName }; try { if (payment.installment) navigation.navigate('PaymentInstallments', { payment }); else navigation.navigate('PaymentReview', { payment: await validatePayment(payment) }); } catch (error) { Alert.alert('Não foi possível validar', error?.message || 'Confira os dados do pagamento.'); } }; return <PaymentLayout navigation={navigation} title="Dados do boleto"><BalanceCard label="Saldo da conta digital" onToggleVisibility={() => setBalance((v) => !v)} style={styles.balance} value={paymentData.balance} variant="blue" visible={balance} /><Card elevated={false} style={styles.card}><PaymentInfoRow label="Código de barras" value={bill.code} /><PaymentInfoRow label="Favorecido" value={bill.beneficiary} /><PaymentInfoRow label="CNPJ" value={bill.beneficiaryDocument} /><PaymentInfoRow label="Vencimento" value={bill.dueDate} /><PaymentInfoRow label="Valor do documento" value={`R$ ${bill.documentValue}`} /><PaymentInfoRow label="Desconto" value={`R$ ${bill.discount}`} /><PaymentInfoRow label="Juros" value={`R$ ${bill.interest}`} /><PaymentInfoRow label="Multa" value={`R$ ${bill.fine}`} last /></Card><PaymentField keyboardType="decimal-pad" label="Valor a pagar" onChangeText={setAmount} value={amount} /><PaymentField label="Descrição" multiline onChangeText={setDescription} value={description} /><PaymentToggle label="Salvar como favorito" onPress={() => setFavorite((v) => !v)} selected={favorite} /><PaymentToggle label="Agendar pagamento" onPress={() => setScheduled((v) => !v)} selected={scheduled} />{scheduled ? <PaymentField keyboardType="numeric" label="Data do pagamento" onChangeText={setDate} placeholder="DD/MM/AAAA" value={date} /> : null}<PrimaryButton onPress={next}>Continuar</PrimaryButton></PaymentLayout>; }
const styles = StyleSheet.create({ balance: { marginBottom: spacing.lg }, card: { backgroundColor: 'rgba(12, 43, 76, 0.72)', borderColor: 'rgba(92, 142, 220, 0.10)', borderWidth: 1, marginBottom: spacing.xl, padding: spacing.lg, shadowColor: '#000000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 4 }, mock: { ...typography.caption, color: colors.textMuted, marginTop: spacing.lg, textAlign: 'center' } });
