import React, { useState } from 'react';
import { Alert, StyleSheet, Text } from 'react-native';
import PaymentLayout from '../../components/payments/PaymentLayout';
import { PaymentField } from '../../components/payments/PaymentForm';
import { PrimaryButton } from '../../components/ui';
import { lookupBarcode } from '../../services/paymentService';
import { colors, spacing, typography } from '../../theme';
import { onlyPaymentDigits, validatePaymentCode } from '../../utils/paymentValidation';
export default function PaymentCodeScreen({ navigation, route }) { const [code, setCode] = useState(route.params?.code || ''); const submit = async () => { if (!validatePaymentCode(code)) return Alert.alert('Código de barras inválido', 'Informe uma linha digitável válida.'); try { navigation.navigate('PaymentDetails', { bill: await lookupBarcode(onlyPaymentDigits(code)), installment: Boolean(route.params?.installment) }); } catch (error) { Alert.alert('Não foi possível consultar', error?.message || 'Confira o código informado.'); } }; return <PaymentLayout navigation={navigation} title="Código de barras"><Text style={styles.title}>Digite o código de barras</Text><Text style={styles.subtitle}>Informe a linha digitável com atenção.</Text><PaymentField keyboardType="numeric" label="Linha digitável" multiline onChangeText={setCode} value={code} /><PrimaryButton onPress={() => setCode('')} style={styles.clear}>Limpar</PrimaryButton><PrimaryButton onPress={submit} style={styles.continue}>Continuar</PrimaryButton><Text style={styles.mock}>Consulta com boleto fictício no ambiente SANDBOX.</Text></PaymentLayout>; }
const styles = StyleSheet.create({ title: { ...typography.heading2, color: colors.textPrimary }, subtitle: { ...typography.body, color: colors.textSecondary, marginBottom: spacing.xl, marginTop: spacing.sm }, clear: { marginBottom: spacing.sm }, continue: { marginTop: spacing.sm }, mock: { ...typography.caption, color: colors.textMuted, marginTop: spacing.lg, textAlign: 'center' } });
