import React, { useState } from 'react';
import { Alert, StyleSheet, Text } from 'react-native';
import PaymentLayout from '../../components/payments/PaymentLayout';
import { PaymentField, PaymentInfoRow, PaymentToggle } from '../../components/payments/PaymentForm';
import { BalanceCard, Card, MissingDataState, PrimaryButton } from '../../components/ui';
import { MOCK_PAYMENT_BALANCE } from '../../data/paymentMockData';
import { colors, spacing, typography } from '../../theme';
import { paymentCurrencyToNumber, validatePaymentDate } from '../../utils/paymentValidation';
export default function PaymentDetailsScreen({ navigation, route }) { const bill = route.params?.bill; const [amount, setAmount] = useState(bill?.total || ''); const [description, setDescription] = useState(''); const [scheduled, setScheduled] = useState(false); const [date, setDate] = useState(''); const [favorite, setFavorite] = useState(false); const [balance, setBalance] = useState(false); if (!bill) return <MissingDataState navigation={navigation} title="Dados do boleto" />; const next = () => { if (paymentCurrencyToNumber(amount) <= 0) return Alert.alert('Informe o valor a pagar'); if (scheduled && !validatePaymentDate(date)) return Alert.alert('Informe uma data válida no formato DD/MM/AAAA'); const payment = { bill: { ...bill, total: amount }, description, scheduled, date, favorite, installment: Boolean(route.params?.installment), favoriteName: route.params?.favoriteName }; navigation.navigate(payment.installment ? 'PaymentInstallments' : 'PaymentReview', { payment }); }; return <PaymentLayout navigation={navigation} title="Dados do boleto"><BalanceCard label="Saldo da conta digital" onToggleVisibility={() => setBalance((v) => !v)} style={styles.balance} value={MOCK_PAYMENT_BALANCE} variant="blue" visible={balance} /><Card style={styles.card}><PaymentInfoRow label="Código de barras" value={bill.code} /><PaymentInfoRow label="Favorecido" value={bill.beneficiary} /><PaymentInfoRow label="CNPJ" value={bill.beneficiaryDocument} /><PaymentInfoRow label="Vencimento" value={bill.dueDate} /><PaymentInfoRow label="Valor do documento" value={`R$ ${bill.documentValue}`} /><PaymentInfoRow label="Desconto" value={`R$ ${bill.discount}`} /><PaymentInfoRow label="Juros" value={`R$ ${bill.interest}`} /><PaymentInfoRow label="Multa" value={`R$ ${bill.fine}`} last /></Card><PaymentField keyboardType="decimal-pad" label="Valor a pagar" onChangeText={setAmount} value={amount} /><PaymentField label="Descrição" multiline onChangeText={setDescription} value={description} /><PaymentToggle label="Salvar como favorito" onPress={() => setFavorite((v) => !v)} selected={favorite} /><PaymentToggle label="Agendar pagamento" onPress={() => setScheduled((v) => !v)} selected={scheduled} />{scheduled ? <PaymentField keyboardType="numeric" label="Data do pagamento" onChangeText={setDate} placeholder="DD/MM/AAAA" value={date} /> : null}<PrimaryButton onPress={next}>Continuar</PrimaryButton><Text style={styles.mock}>Beneficiário e encargos retornados por mock local.</Text></PaymentLayout>; }
const styles = StyleSheet.create({ balance: { marginBottom: spacing.lg }, card: { marginBottom: spacing.xl, padding: spacing.lg }, mock: { ...typography.caption, color: colors.textMuted, marginTop: spacing.lg, textAlign: 'center' } });
