import React from 'react';
import { Alert, Share, StyleSheet, Text } from 'react-native';
import TransferLayout from '../../components/transfers/TransferLayout';
import { TransferInfoRow } from '../../components/transfers/TransferForm';
import { Card, ConfirmationButton, MissingDataState, OutlineButton, PrimaryButton } from '../../components/ui';
import { colors, radii, spacing, typography } from '../../theme';

export default function TransferReceiptScreen({ navigation, route }) {
  const transfer = route.params?.transfer; if (!transfer) return <MissingDataState navigation={navigation} title="Comprovante" />; const message = `Transferência ${transfer.simulated ? 'SANDBOX simulada' : 'realizada'}\nValor: R$ ${transfer.amount}\nFavorecido: ${transfer.beneficiary.name}\nIdentificador: ${transfer.sandboxReference || transfer.id}`;
  return <TransferLayout navigation={navigation} title="Comprovante"><Text style={styles.success}>✓</Text><Text style={{ color: colors.textMuted, textAlign: 'center', marginTop: spacing.sm }}>{transfer.simulated ? `${transfer.scheduled ? 'AGENDAMENTO SANDBOX' : 'COMPROVANTE SANDBOX'} · OPERAÇÃO SIMULADA` : 'Ambiente de demonstração'}</Text><Text style={styles.title}>{transfer.scheduled ? 'Transferência agendada!' : 'Transferência realizada!'}</Text>{transfer.scheduled && transfer.simulated ? <Text style={{ color: colors.confirmation, textAlign: 'center', marginTop: spacing.sm }}>NÃO SERÁ EXECUTADA AUTOMATICAMENTE</Text> : null}<Text style={styles.amount}>R$ {transfer.amount}</Text><Card style={styles.card}><TransferInfoRow label="Favorecido" value={transfer.beneficiary.name} /><TransferInfoRow label="Instituição" value={transfer.beneficiary.bank} /><TransferInfoRow label="Agência e conta" value={`${transfer.beneficiary.agency} · ${transfer.beneficiary.account}-${transfer.beneficiary.digit}`} /><TransferInfoRow label="Data" value={transfer.scheduled ? transfer.date : 'Hoje'} /><TransferInfoRow label="Identificador" value={transfer.sandboxReference || transfer.id} last /></Card><ConfirmationButton onPress={() => Share.share({ message })}>Compartilhar</ConfirmationButton><PrimaryButton onPress={() => Alert.alert(transfer.simulated ? 'Comprovante SANDBOX' : 'Comprovante mock', transfer.simulated ? 'Operação simulada. Não existe PDF bancário oficial.' : 'O PDF depende da API original.')} style={styles.button}>Visualizar comprovante</PrimaryButton><OutlineButton onPress={() => navigation.navigate('Transfers')} style={styles.button}>Voltar às transferências</OutlineButton></TransferLayout>;
}
const styles = StyleSheet.create({ success: { alignSelf: 'center', backgroundColor: 'rgba(46,207,146,0.16)', borderRadius: radii.pill, color: colors.success, fontSize: 48, marginTop: spacing.md, overflow: 'hidden', paddingHorizontal: spacing.lg }, title: { ...typography.heading2, color: colors.textPrimary, marginTop: spacing.md, textAlign: 'center' }, amount: { ...typography.display, color: colors.textPrimary, marginBottom: spacing.xl, marginTop: spacing.sm, textAlign: 'center' }, card: { marginBottom: spacing.xl, padding: spacing.lg }, button: { marginTop: spacing.md } });
