import React from 'react';
import { Alert, Share, StyleSheet, Text } from 'react-native';
import TransferLayout from '../../components/transfers/TransferLayout';
import { TransferInfoRow } from '../../components/transfers/TransferForm';
import { Card, ConfirmationButton, Icon, MissingDataState, OutlineButton, PrimaryButton } from '../../components/ui';
import { colors, spacing, typography } from '../../theme';

export default function TransferReceiptScreen({ navigation, route }) {
  const transfer = route.params?.transfer; if (!transfer) return <MissingDataState navigation={navigation} title="Comprovante" />; const message = `Transferência realizada\nValor: R$ ${transfer.amount}\nFavorecido: ${transfer.beneficiary.name}\nIdentificador: ${transfer.sandboxReference || transfer.id}`;
  return <TransferLayout navigation={navigation} title="Comprovante"><Icon color={colors.purple400} name="checkmark-circle" size={48} style={styles.success} /><Text style={styles.title}>{transfer.scheduled ? 'Transferência agendada!' : 'Transferência realizada!'}</Text>{transfer.scheduled && transfer.simulated ? <Text style={{ color: colors.confirmation, textAlign: 'center', marginTop: spacing.sm }}>NÃO SERÁ EXECUTADA AUTOMATICAMENTE</Text> : null}<Text style={styles.amount}>R$ {transfer.amount}</Text><Card elevated={false} style={styles.card}><TransferInfoRow label="Favorecido" value={transfer.beneficiary.name} /><TransferInfoRow label="Instituição" value={transfer.beneficiary.bank} /><TransferInfoRow label="Agência e conta" value={`${transfer.beneficiary.agency} · ${transfer.beneficiary.account}-${transfer.beneficiary.digit}`} /><TransferInfoRow label="Data" value={transfer.scheduled ? transfer.date : 'Hoje'} /><TransferInfoRow label="Identificador" value={transfer.sandboxReference || transfer.id} last /></Card><ConfirmationButton onPress={() => Share.share({ message })}>Compartilhar</ConfirmationButton><PrimaryButton onPress={() => Alert.alert('Comprovante', 'O PDF depende da API original.')} style={styles.button}>Visualizar comprovante</PrimaryButton><OutlineButton onPress={() => navigation.navigate('Transfers')} style={styles.button}>Voltar às transferências</OutlineButton></TransferLayout>;
}
const styles = StyleSheet.create({ success: { alignSelf: 'center', marginTop: spacing.md }, title: { ...typography.heading2, color: colors.textPrimary, marginTop: spacing.md, textAlign: 'center' }, amount: { ...typography.display, color: colors.textPrimary, marginBottom: spacing.xl, marginTop: spacing.sm, textAlign: 'center' }, card: { backgroundColor: 'rgba(12, 43, 76, 0.72)', borderColor: 'rgba(92, 142, 220, 0.10)', borderWidth: 1, marginBottom: spacing.xl, padding: spacing.lg, shadowColor: '#000000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 4 }, button: { marginTop: spacing.md } });
