import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import StatementLayout from '../../components/statement/StatementLayout';
import { PrimaryButton, SectionTitle } from '../../components/ui';
import { colors, radii, shadows, spacing, typography } from '../../theme';
import { isValidDateRange } from '../../utils/dateValidation';
const PERIODS = [1, 7, 15, 30, 60, 90]; const DIRECTIONS = [{ id: 'todos', label: 'Todos' }, { id: 'entrada', label: 'Entradas' }, { id: 'saida', label: 'Saídas' }]; const CATEGORIES = ['todos', 'Pix', 'Transferência', 'Pagamento', 'Serviços', 'Crédito'];
function Chips({ items, selected, onSelect, renderLabel = (item) => String(item) }) { return <View style={styles.chips}>{items.map((item) => { const id = item.id || item; return <TouchableOpacity key={id} onPress={() => onSelect(id)} style={[styles.chip, selected === id && styles.active]}><Text style={[styles.chipText, selected === id && styles.activeText]}>{renderLabel(item)}</Text></TouchableOpacity>; })}</View>; }
export default function StatementFiltersScreen({ navigation, route }) { const current = route.params?.current || {}; const [period, setPeriod] = useState(current.period || 30); const [direction, setDirection] = useState(current.direction || 'todos'); const [category, setCategory] = useState(current.category || 'todos'); const [startDate, setStartDate] = useState(current.startDate || ''); const [endDate, setEndDate] = useState(current.endDate || ''); const apply = () => { if ((startDate || endDate) && !isValidDateRange(startDate, endDate)) return Alert.alert('Período inválido', 'Informe datas válidas e uma data final igual ou posterior à inicial.'); navigation.navigate('Statement', { appliedFilters: { category, direction, endDate, period, startDate }, filterVersion: Date.now() }); }; return <StatementLayout atmospheric backgroundSource={require('../../../assets/ctbx-statement-background.png')} navigation={navigation} title="Filtros"><SectionTitle title="Período rápido" /><Chips items={PERIODS} onSelect={(value) => { setPeriod(value); setStartDate(''); setEndDate(''); }} renderLabel={(item) => item === 1 ? 'Hoje' : `${item} dias`} selected={period} /><SectionTitle style={styles.section} title="Período personalizado" /><TextInput keyboardType="numeric" onChangeText={setStartDate} placeholder="Data início · DD/MM/AAAA" placeholderTextColor={colors.textMuted} style={styles.input} value={startDate} /><TextInput keyboardType="numeric" onChangeText={setEndDate} placeholder="Data fim · DD/MM/AAAA" placeholderTextColor={colors.textMuted} style={styles.input} value={endDate} /><SectionTitle style={styles.section} title="Filtrar por" /><Chips items={DIRECTIONS} onSelect={setDirection} renderLabel={(item) => item.label} selected={direction} /><SectionTitle style={styles.section} title="Categoria" /><Chips items={CATEGORIES} onSelect={setCategory} renderLabel={(item) => item === 'todos' ? 'Todas' : item} selected={category} /><PrimaryButton onPress={apply} style={styles.apply}>Aplicar filtros</PrimaryButton></StatementLayout>; }
// "Dark glass": mesma linguagem visual do Extrato — fundo translúcido em vez
// de cor sólida, borda quase invisível, e a aba/chip ativa marcada só por
// borda + glow (sem preenchimento roxo sólido).
const styles = StyleSheet.create({ chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, chip: { backgroundColor: 'rgba(12, 43, 76, 0.6)', borderColor: 'rgba(92, 142, 220, 0.10)', borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.md }, active: { backgroundColor: 'rgba(12, 43, 76, 0.6)', borderColor: 'rgba(99, 102, 241, 0.55)', ...shadows.glowPurple }, chipText: { ...typography.caption, color: colors.textSecondary }, activeText: { color: colors.purple300, fontWeight: '700' }, section: { marginTop: spacing.xxl }, input: { backgroundColor: 'rgba(16, 51, 85, 0.72)', borderColor: 'rgba(92, 142, 220, 0.08)', borderRadius: radii.md, borderWidth: 1, color: colors.textPrimary, marginTop: spacing.md, minHeight: 54, paddingHorizontal: spacing.lg }, apply: { marginTop: spacing.xxxl } });
