import React, { useCallback } from 'react';
import { StyleSheet, Text } from 'react-native';
import StatementLayout from '../../components/statement/StatementLayout';
import { Card, ConfirmationButton, ErrorState, LoadingState, MissingDataState, OutlineButton } from '../../components/ui';
import useAsyncResource from '../../hooks/useAsyncResource';
import { getTransaction } from '../../services/statementService';
import { colors, spacing, typography } from '../../theme';
import { formatStatementAmount } from '../../utils/statementUtils';
function Row({ label, value }) { return <Text style={styles.row}><Text style={styles.label}>{label}{'\n'}</Text>{value || '—'}</Text>; }
export default function StatementDetailScreen({ navigation, route }) { const transaction = route.params?.transaction; const load = useCallback(() => getTransaction(transaction), [transaction]); const { data: item, error, loading, retry } = useAsyncResource(load); if (!transaction) return <MissingDataState navigation={navigation} title="Detalhe da movimentação" />; if (loading) return <StatementLayout navigation={navigation} title="Detalhe da movimentação"><LoadingState /></StatementLayout>; if (error?.status === 404) return <MissingDataState navigation={navigation} title="Movimentação não encontrada" />; if (error) return <StatementLayout navigation={navigation} title="Detalhe da movimentação"><ErrorState message="Não foi possível carregar a movimentação." onRetry={retry} /></StatementLayout>; if (!item) return <MissingDataState navigation={navigation} title="Movimentação não encontrada" />; const incoming = item.direction === 'entrada'; return <StatementLayout navigation={navigation} title="Detalhe da movimentação"><Text style={[styles.amount, incoming ? styles.positive : styles.negative]}>{incoming ? '+' : '-'} R$ {formatStatementAmount(item.amount)}</Text><Text style={styles.status}>{item.status}</Text><Card style={styles.card}><Row label="Operação" value={item.description} /><Row label="Data e hora" value={`${item.date} às ${item.time}`} /><Row label={incoming ? 'Origem' : 'Beneficiário'} value={item.counterparty} /><Row label="Instituição" value={item.bank} /><Row label="Documento" value={item.document} /><Row label="Categoria" value={item.category} /><Row label="Identificador" value={item.id} /><Row label="Tarifa" value={`R$ ${item.fee}`} />{item.reason ? <Row label="Motivo" value={item.reason} /> : null}</Card>{item.receipt ? <ConfirmationButton onPress={() => navigation.navigate('StatementReceipt', { transaction: item })}>Ver comprovante</ConfirmationButton> : null}{item.status === 'Em análise' ? <OutlineButton onPress={() => navigation.navigate('StatementBlockedResponse', { transaction: item })} style={styles.button}>Responder análise</OutlineButton> : null}<OutlineButton onPress={() => navigation.goBack()} style={styles.button}>Voltar</OutlineButton></StatementLayout>; }
const styles = StyleSheet.create({ amount: { ...typography.display, marginTop: spacing.lg, textAlign: 'center' }, positive: { color: colors.success }, negative: { color: colors.orange400 }, status: { ...typography.bodyMedium, color: colors.textSecondary, marginBottom: spacing.xl, marginTop: spacing.sm, textAlign: 'center' }, card: { marginBottom: spacing.xl, padding: spacing.lg }, row: { ...typography.bodyMedium, borderBottomColor: colors.borderSubtle, borderBottomWidth: 1, color: colors.textPrimary, paddingVertical: spacing.md }, label: { ...typography.caption, color: colors.textSecondary }, button: { marginTop: spacing.md } });
