import { MOCK_PIX_BALANCE, MOCK_PIX_BENEFICIARY, MOCK_PIX_FAVORITES, MOCK_PIX_KEYS, PIX_KEY_TYPES, buildMockPixTransfer } from '../data/pixMockData';
import { demoOrThrow } from './serviceMode';
export const getBalance = () => demoOrThrow(() => MOCK_PIX_BALANCE);
export const lookupKey = () => demoOrThrow(() => MOCK_PIX_BENEFICIARY);
export const listFavorites = () => demoOrThrow(() => MOCK_PIX_FAVORITES);
export const listKeys = () => demoOrThrow(() => MOCK_PIX_KEYS);
export const createTransfer = (input) => demoOrThrow(() => buildMockPixTransfer(input));
export const lookupQrCode = (input) => demoOrThrow(() => buildMockPixTransfer(input));
export const getFavorites = listFavorites; export const getKeys = listKeys;
export const getAvailableKeyTypes = () => demoOrThrow(() => PIX_KEY_TYPES);
export const createKey = (key) => demoOrThrow(() => ({ ...key, id: `DEMO-KEY-${Date.now()}`, status: 'Ativo' }));
export const deleteKey = (key) => demoOrThrow(() => key);
export const generateReceiveQr = (input) => demoOrThrow(() => ({ ...input, payload: `PIX-DEMO|${input.keyValue}|${input.amount || '0,00'}` }));
export const validateTransfer = (transfer) => demoOrThrow(() => transfer);
export const authorizeTransfer = (transfer) => demoOrThrow(() => ({ ...transfer, demoMode: true }));
export const scheduleTransfer = authorizeTransfer;
export const getReceipt = (transfer) => demoOrThrow(() => transfer);
export const getPixTransferData = () => demoOrThrow(() => ({ balance: MOCK_PIX_BALANCE }));
