import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { BottomTabBar, Card, Screen, SectionTitle } from '../../components/ui';
import FinancialCard from '../../components/cards/FinancialCard';
import { MOCK_FINANCIAL_CARD, MOCK_TRANSPORT_CARD } from '../../data/cardMockData';
import { colors, spacing, typography } from '../../theme';

const ACTIONS=[['Detalhes','CardDetails'],['Ativar cartão','CardActivation'],['Recarregar','CardRecharge'],['Trocar senha','CardPassword'],['Bloquear cartão','CardSecurity'],['Extrato','CardStatement'],['Comprovantes','CardReceipts'],['Solicitar cartão','CardRequest']];
export default function CardsScreen({navigation}){
 return <Screen><View style={styles.header}><Text style={styles.title}>Meus cartões</Text><Text style={styles.sub}>Gerencie seus cartões CTBX</Text></View><ScrollView contentContainerStyle={styles.bodyContent} style={styles.body} showsVerticalScrollIndicator={false}><FinancialCard card={MOCK_FINANCIAL_CARD}/><Text style={styles.balance}>Saldo disponível  <Text style={styles.amount}>{MOCK_FINANCIAL_CARD.balance}</Text></Text><SectionTitle title="Serviços do cartão"/><View style={styles.grid}>{ACTIONS.map(([label,route])=><TouchableOpacity key={route} onPress={()=>navigation.navigate(route)} style={styles.action}><Text style={styles.icon}>◇</Text><Text style={styles.actionText}>{label}</Text></TouchableOpacity>)}</View><SectionTitle title="Cartão de transporte"/><TouchableOpacity onPress={()=>navigation.navigate('TransportCard')}><Card style={styles.transport}><View><Text style={styles.transportTitle}>TOP Transporte</Text><Text style={styles.muted}>•••• {MOCK_TRANSPORT_CARD.lastFour} · {MOCK_TRANSPORT_CARD.status}</Text></View><Text style={styles.amount}>{MOCK_TRANSPORT_CARD.balance}</Text></Card></TouchableOpacity></ScrollView><BottomTabBar activeKey="cards" onTabPress={(tab)=>{if(tab.key==='home')navigation.navigate('Home');if(tab.key==='services')navigation.navigate('Services');if(tab.key==='pix')navigation.navigate('Pix');if(tab.key==='profile')navigation.navigate('Profile')}}/></Screen>
}
const styles=StyleSheet.create({header:{padding:spacing.xl},title:{...typography.heading1,color:colors.textPrimary},sub:{...typography.body,color:colors.textSecondary,marginTop:4},body:{flex:1},bodyContent:{paddingBottom:spacing.xxxl,paddingHorizontal:spacing.lg},balance:{...typography.body,color:colors.textSecondary,marginVertical:spacing.lg},amount:{color:colors.textPrimary,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginBottom:spacing.lg},action:{alignItems:'center',backgroundColor:colors.surface,borderColor:colors.border,borderRadius:16,borderWidth:1,minHeight:88,padding:spacing.md,width:'48%'},icon:{color:colors.purple400,fontSize:24},actionText:{color:colors.textPrimary,fontWeight:'600',marginTop:6,textAlign:'center'},transport:{alignItems:'center',flexDirection:'row',justifyContent:'space-between',marginBottom:spacing.lg},transportTitle:{...typography.heading3,color:colors.textPrimary},muted:{...typography.caption,color:colors.textSecondary,marginTop:4}});
