import React from 'react';
import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { BottomTabBar, EmptyState, ErrorState, Icon, LoadingState, Screen, SectionTitle } from '../../components/ui';
import FinancialCard from '../../components/cards/FinancialCard';
import { getCards } from '../../services/cardService';
import useAsyncResource from '../../hooks/useAsyncResource';
import { colors, spacing, typography } from '../../theme';
const ACTIONS = [['Detalhes', 'CardDetails', 'information-circle-outline'], ['Ativar cartão', 'CardActivation', 'checkmark-circle-outline'], ['Recarregar', 'CardRecharge', 'add-circle-outline'], ['Trocar senha', 'CardPassword', 'key-outline'], ['Bloquear cartão', 'CardSecurity', 'lock-closed-outline'], ['Extrato', 'CardStatement', 'reader-outline'], ['Comprovantes', 'CardReceipts', 'receipt-outline'], ['Solicitar cartão', 'CardRequest', 'card-outline']];
export default function CardsScreen({ navigation }) { const { data: cards, error, loading, retry } = useAsyncResource(getCards, []); if (loading) return <Screen><LoadingState label="Carregando cartões…" /></Screen>; if (error) return <Screen><ErrorState message="Não foi possível carregar os cartões." onRetry={retry} /></Screen>; if (!cards.length) return <Screen><EmptyState message="Nenhum cartão disponível." /></Screen>; const [financialCard, transportCard] = cards; return <Screen atmospheric backgroundSource={require('../../../assets/ctbx-investments-background.png')} gradient={false}><View style={styles.header}><Text style={styles.title}>Meus cartões</Text><Text style={styles.sub}>Gerencie seus cartões CTBX</Text></View><ScrollView contentContainerStyle={styles.bodyContent} style={styles.body} showsVerticalScrollIndicator={false}><FinancialCard card={financialCard} /><Text style={styles.balance}>Saldo disponível  <Text style={styles.amount}>{financialCard.balance}</Text></Text><SectionTitle title="Serviços do cartão" /><View style={styles.grid}>{ACTIONS.map(([label, route, icon]) => <TouchableOpacity key={route} onPress={() => navigation.navigate(route)} style={styles.action}><Icon color={colors.purple400} name={icon} size={22} /><Text style={styles.actionText}>{label}</Text></TouchableOpacity>)}</View>{transportCard ? <><SectionTitle title="Cartão de transporte" /><TouchableOpacity accessibilityLabel="Abrir cartão de transporte" onPress={() => navigation.navigate('TransportCard')} style={styles.transport}><Image resizeMode="cover" source={require('../../../assets/ctbx-card-transport.png')} style={styles.transportImage} /></TouchableOpacity></> : null}</ScrollView><BottomTabBar activeKey="cards" onTabPress={(tab) => { if (tab.key === 'home') navigation.navigate('Home'); if (tab.key === 'services') navigation.navigate('Services'); if (tab.key === 'pix') navigation.navigate('Pix'); if (tab.key === 'profile') navigation.navigate('Profile'); }} /></Screen>; }
// "Dark glass": mesma linguagem visual do Extrato/Investimentos/Home — fundo
// translúcido em vez de cor sólida, borda quase invisível, sombra própria.
const styles = StyleSheet.create({ header: { backgroundColor: 'transparent', padding: spacing.xl }, title: { ...typography.heading1, color: colors.textPrimary }, sub: { ...typography.body, color: colors.textSecondary, marginTop: 4 }, body: { backgroundColor: 'transparent', flex: 1 }, bodyContent: { backgroundColor: 'transparent', paddingBottom: spacing.xxxl, paddingHorizontal: spacing.lg }, balance: { ...typography.body, color: colors.textSecondary, marginVertical: spacing.lg }, amount: { color: colors.textPrimary, fontWeight: '800' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.lg }, action: { alignItems: 'center', backgroundColor: 'rgba(12, 43, 76, 0.72)', borderColor: 'rgba(92, 142, 220, 0.10)', borderRadius: 16, borderWidth: 1, minHeight: 88, padding: spacing.md, shadowColor: '#000000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 4, width: '48%' }, actionText: { color: colors.textPrimary, fontWeight: '600', marginTop: 6, textAlign: 'center' }, transport: { aspectRatio: 1638 / 960, borderColor: colors.purple400, borderRadius: 20, borderWidth: 1, marginBottom: spacing.lg, overflow: 'hidden', width: '100%' }, transportImage: { height: '100%', width: '100%' } });
