import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import CardScreenLayout from '../../components/cards/CardScreenLayout';
import { Card, ConfirmationButton } from '../../components/ui';
import { rechargeCard } from '../../services/cardService';
import { colors, spacing, typography } from '../../theme';
import { validMoney } from '../../utils/cardUtils';
export default function CardRechargeScreen({ navigation, route }) { const [value, setValue] = useState(''); const [loading, setLoading] = useState(false); const transport = route.params?.transport; const submit = async () => { if (!validMoney(value)) return Alert.alert('Valor inválido', 'Informe um valor maior que zero.'); try { setLoading(true); await rechargeCard(value, { transport }); Alert.alert('COMPROVANTE SANDBOX', 'OPERAÇÃO SIMULADA.', [{ text: 'OK', onPress: () => navigation.goBack() }]); } catch (error) { Alert.alert('Serviço indisponível', error?.message || 'A recarga não foi concluída.'); } finally { setLoading(false); } }; return <CardScreenLayout navigation={navigation} title={transport ? 'Recarregar TOP' : 'Recarregar cartão'}><View style={styles.wrap}><Card><Text style={styles.title}>{transport ? 'Crédito de transporte' : 'Recarga do cartão'}</Text><Text style={styles.copy}>Operação exclusivamente simulada no ambiente SANDBOX.</Text><TextInput value={value} onChangeText={setValue} keyboardType="decimal-pad" placeholder="R$ 0,00" placeholderTextColor={colors.textMuted} style={styles.input} /></Card><ConfirmationButton disabled={loading} loading={loading} onPress={submit}>Confirmar recarga</ConfirmationButton></View></CardScreenLayout>; }
const styles = StyleSheet.create({ wrap: { gap: spacing.lg, padding: spacing.lg }, title: { ...typography.heading2, color: colors.textPrimary }, copy: { ...typography.body, color: colors.textSecondary, marginVertical: spacing.md }, input: { backgroundColor: colors.surfaceElevated, borderColor: colors.border, borderRadius: 14, borderWidth: 1, color: colors.textPrimary, padding: spacing.md } });
