import React, { useState } from 'react';
import { Alert, StyleSheet, TextInput, View } from 'react-native';
import CardScreenLayout from '../../components/cards/CardScreenLayout';
import { Card, ConfirmationButton } from '../../components/ui';
import { colors, spacing } from '../../theme';
import { validCardPassword } from '../../utils/cardUtils';
import { changePassword } from '../../services/cardService';
export default function CardPasswordScreen({ navigation }) { const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const done = async () => { if (!validCardPassword(current) || !validCardPassword(next) || next !== confirm) return Alert.alert('Confira as senhas', 'Todas devem ter 4 números e a confirmação deve coincidir.'); try { setLoading(true); await changePassword(next); Alert.alert('Senha alterada', 'COMPROVANTE SANDBOX · OPERAÇÃO SIMULADA.', [{ text: 'OK', onPress: () => navigation.goBack() }]); } catch (error) { Alert.alert('Serviço indisponível', error?.message || 'A troca de senha não foi concluída.'); } finally { setLoading(false); } }; return <CardScreenLayout navigation={navigation} title="Trocar senha"><View style={styles.wrap}><Card>{[['Senha atual', current, setCurrent], ['Nova senha', next, setNext], ['Confirmar nova senha', confirm, setConfirm]].map(([placeholder, value, setter]) => <TextInput key={placeholder} value={value} onChangeText={setter} secureTextEntry keyboardType="number-pad" placeholder={placeholder} placeholderTextColor={colors.textMuted} style={styles.input} />)}</Card><ConfirmationButton disabled={loading} loading={loading} title="Alterar senha" onPress={done} /></View></CardScreenLayout>; }
const styles = StyleSheet.create({ wrap: { gap: spacing.lg, padding: spacing.lg }, input: { backgroundColor: colors.surfaceElevated, borderColor: colors.border, borderRadius: 14, borderWidth: 1, color: colors.textPrimary, marginVertical: spacing.xs, padding: spacing.md } });
