import React from 'react';
import { Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { BottomTabBar, Card, EmptyState, ErrorState, LoadingState, OutlineButton, Screen, SectionTitle } from '../../components/ui';
import ProfileRow from '../../components/profile/ProfileRow';
import { getProfile } from '../../services/profileService';
import useAsyncResource from '../../hooks/useAsyncResource';
import { colors, spacing, typography } from '../../theme';
import { useSession } from '../../session';

export default function ProfileScreen({ navigation }) {
  const { logout: clearSession } = useSession();
  const { data: profile, error, loading, retry } = useAsyncResource(getProfile);
  const logout = () => Alert.alert('Sair da conta', 'Deseja realmente sair?', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Sair', style: 'destructive', onPress: clearSession }]);
  if (loading) return <Screen><LoadingState label="Carregando perfil…" /></Screen>;
  if (error) return <Screen><ErrorState message="Não foi possível carregar o perfil." onRetry={retry} /></Screen>;
  if (!profile) return <Screen><EmptyState message="Perfil não encontrado." /></Screen>;
  return <Screen><View style={styles.body}><View style={styles.identity}><TouchableOpacity onPress={() => navigation.navigate('ProfilePhoto')}><Image source={require('../../../assets/legacy/assets_images_avatar.png')} style={styles.avatar} /><Text style={styles.edit}>Alterar foto</Text></TouchableOpacity><View style={styles.identityText}><Text style={styles.name}>{profile.name}</Text><Text style={styles.email}>{profile.email}</Text></View></View><ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}><SectionTitle>Minha conta</SectionTitle><Card style={styles.card}><ProfileRow icon="●" label="Dados pessoais" onPress={() => navigation.navigate('ProfilePersonalData')} /><ProfileRow icon="▣" label="Dados da conta" onPress={() => navigation.navigate('ProfileAccountData')} /></Card><SectionTitle>Segurança</SectionTitle><Card style={styles.card}><ProfileRow icon="◉" label="Biometria" onPress={() => navigation.navigate('ProfileBiometrics')} /><ProfileRow icon="▱" label="Dispositivos" onPress={() => navigation.navigate('ProfileDevices')} /><ProfileRow icon="#" label="Token" onPress={() => navigation.navigate('ProfileToken')} /></Card><SectionTitle>Informações</SectionTitle><Card style={styles.card}><ProfileRow icon="§" label="Meus termos" onPress={() => navigation.navigate('ProfileTerms')} /><ProfileRow icon="?" label="Ajuda" onPress={() => navigation.navigate('ServiceInfo', { type: 'help' })} /></Card><OutlineButton onPress={logout} style={styles.logout}>Sair da conta</OutlineButton></ScrollView></View><BottomTabBar activeKey="profile" onTabPress={(tab) => { if (tab.key === 'home') navigation.navigate('Home'); if (tab.key === 'cards') navigation.navigate('Cards'); if (tab.key === 'services') navigation.navigate('Services'); if (tab.key === 'pix') navigation.navigate('Pix'); }} /></Screen>;
}
const styles = StyleSheet.create({ body: { flex: 1 }, identity: { alignItems: 'center', flexDirection: 'row', padding: spacing.xl }, avatar: { backgroundColor: colors.surfaceElevated, borderColor: colors.purple400, borderRadius: 40, borderWidth: 2, height: 80, width: 80 }, edit: { ...typography.caption, color: colors.purple300, marginTop: 4, textAlign: 'center' }, identityText: { flex: 1, marginLeft: spacing.lg }, name: { ...typography.heading2, color: colors.textPrimary }, email: { ...typography.body, color: colors.textSecondary, marginTop: 4 }, list: { gap: spacing.md, paddingBottom: spacing.xxl, paddingHorizontal: spacing.lg }, card: { paddingBottom: 0, paddingTop: 0 }, logout: { borderColor: colors.orange500, marginVertical: spacing.lg } });
